# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookBuyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='ISBN',
            new_name='Book',
        ),
        migrations.AddField(
            model_name='cost',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookBuyer.Book'),
        ),
    ]
