# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-29 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookBuyer', '0002_auto_20160815_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
